# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: btorp <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/10 16:47:44 by btorp             #+#    #+#              #
#    Updated: 2019/02/10 16:49:31 by btorp            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRS = ../*.c
CHECKTETRA = ../ft_check_tetra.c
LIB = ../../../libft/*.c
TESTS = *.c
HEADERS = ../dlst/dlst.h ../../../libft/libft.h
all:
	gcc $(CHECKTETRA) $(LIB) $(TESTS) -I $(HEADERS) -g